#ifndef _DEV_MOTOR_CONFIG_H__
#define _DEV_MOTOR_CONFIG_H__

#include "stdlib.h"

#include "rfl_config.h"

/* 电机模块通用参数 --------------------------- */

#define RFL_MOTOR_DEFAULT_ANGLE_RANGE (360.0f)

// 默认电机PID参数
#define RFL_MOTOR_DEFAULT_SPEED_PID_KP (0.0f)
#define RFL_MOTOR_DEFAULT_SPEED_PID_KI (0.0f)
#define RFL_MOTOR_DEFAULT_SPEED_PID_KD (0.0f)
#define RFL_MOTOR_DEFAULT_SPEED_PID_MAX_IOUT (0.0f)
#define RFL_MOTOR_DEFAULT_SPEED_PID_MAX_OUT (0.0f)
#define RFL_MOTOR_DEFAULT_ANGLE_PID_KP (0.0f)
#define RFL_MOTOR_DEFAULT_ANGLE_PID_KI (0.0f)
#define RFL_MOTOR_DEFAULT_ANGLE_PID_KD (0.0f)
#define RFL_MOTOR_DEFAULT_ANGLE_PID_MAX_IOUT (0.0f)
#define RFL_MOTOR_DEFAULT_ANGLE_PID_MAX_OUT (0.0f)

/* 使用RM官方电机 */
#if (RFL_DEV_MOTOR_RM_MOTOR == 1)

// RM M2006 PID参数
#define RFL_MOTOR_RM_M2006_DEFAULT_ANGLE_PID_KP (1.0f)
#define RFL_MOTOR_RM_M2006_DEFAULT_ANGLE_PID_KI (0.0f)
#define RFL_MOTOR_RM_M2006_DEFAULT_ANGLE_PID_KD (0.2f)
#define RFL_MOTOR_RM_M2006_DEFAULT_ANGLE_PID_MAX_IOUT (0.0f)
#define RFL_MOTOR_RM_M2006_DEFAULT_ANGLE_PID_MAX_OUT (24.0f)
#define RFL_MOTOR_RM_M2006_DEFAULT_SPEED_PID_KP (2500.0f)
#define RFL_MOTOR_RM_M2006_DEFAULT_SPEED_PID_KI (250.0f)
#define RFL_MOTOR_RM_M2006_DEFAULT_SPEED_PID_KD (0.0f)
#define RFL_MOTOR_RM_M2006_DEFAULT_SPEED_PID_MAX_IOUT (2500.0f)
#define RFL_MOTOR_RM_M2006_DEFAULT_SPEED_PID_MAX_OUT (10000.0f)

// RM M3508 PID参数
#define RFL_MOTOR_RM_M3508_DEFAULT_ANGLE_PID_KP (0.8f)
#define RFL_MOTOR_RM_M3508_DEFAULT_ANGLE_PID_KI (0.0f)
#define RFL_MOTOR_RM_M3508_DEFAULT_ANGLE_PID_KD (0.0f)
#define RFL_MOTOR_RM_M3508_DEFAULT_ANGLE_PID_MAX_IOUT (0.0f)
#define RFL_MOTOR_RM_M3508_DEFAULT_ANGLE_PID_MAX_OUT (16.0f)
#define RFL_MOTOR_RM_M3508_DEFAULT_SPEED_PID_KP (1200.0f)
#define RFL_MOTOR_RM_M3508_DEFAULT_SPEED_PID_KI (12.0f)
#define RFL_MOTOR_RM_M3508_DEFAULT_SPEED_PID_KD (0.0f)
#define RFL_MOTOR_RM_M3508_DEFAULT_SPEED_PID_MAX_IOUT (4000.0f)
#define RFL_MOTOR_RM_M3508_DEFAULT_SPEED_PID_MAX_OUT (16000.0f)

// RM GM6020 PID参数
#define RFL_MOTOR_RM_GM6020_DEFAULT_ANGLE_PID_KP (1.0f)
#define RFL_MOTOR_RM_GM6020_DEFAULT_ANGLE_PID_KI (0.0f)
#define RFL_MOTOR_RM_GM6020_DEFAULT_ANGLE_PID_KD (0.0f)
#define RFL_MOTOR_RM_GM6020_DEFAULT_ANGLE_PID_MAX_IOUT (0.0f)
#define RFL_MOTOR_RM_GM6020_DEFAULT_ANGLE_PID_MAX_OUT (42.0f)
#define RFL_MOTOR_RM_GM6020_DEFAULT_SPEED_PID_KP (500.0f)
#define RFL_MOTOR_RM_GM6020_DEFAULT_SPEED_PID_KI (50.0f)
#define RFL_MOTOR_RM_GM6020_DEFAULT_SPEED_PID_KD (0.0f)
#define RFL_MOTOR_RM_GM6020_DEFAULT_SPEED_PID_MAX_IOUT (20000.0f)
#define RFL_MOTOR_RM_GM6020_DEFAULT_SPEED_PID_MAX_OUT (30000.0f)

#endif /* RFL_DEV_MOTOR_RM_MOTOR == 1 */

#endif /* _DEV_MOTOR_CONFIG_H__ */
