#ifndef _APP_SCARA_ARM_CONFIG_H__
#define _APP_SCARA_ARM_CONFIG_H__

#include "dev_motor.h"

#include "algo_angle.h"

// typedef struct RflScaraArmJointConfig
// {
//     uint8_t motor_num;

//     rfl_motor_type_e motor_type;
//     rfl_motor_controller_type_e controller_type;
//     bool is_reversed;

//     float max_deg_angle;
//     float min_deg_angle;

//     const rfl_angle_s *external_angle;

//     float angle_pid_param[5];
//     float speed_pid_param[5];
//     float unitree_k_a;
//     float unitree_k_s;

//     uint8_t can_ordinal;
//     uint32_t can_id;
//     uint16_t unitree_motor_id;
// } rfl_scara_arm_joint_config_s;

typedef struct RflScaraArmConfig
{
    /* 基础参数 */
    /**
     * @brief   数组顺序代表由参考坐标系运动到目标坐标系的运动顺序
     * [0:2]    沿X、Y、Z轴平动的距离 沿轴正方向为正 单位 米（m）
     * [3:5]    绕Z、Y、X轴旋转的角度 逆时针为正 单位 弧度（rad）
     */
    float j1_to_base_pose_6d[6]; // 关节1坐标系在基坐标系下的位姿
    float tool_to_j6_pose_6d[6]; // 工具坐标系在关节6坐标系下的位姿

    float dh[6][5]; // Scara构型机械臂DH参数

} rfl_scara_arm_config_s;

#define RFL_SCARA_ARM_JI_TO_BASE_DEFAULT_X (0.0f)
#define RFL_SCARA_ARM_JI_TO_BASE_DEFAULT_Y (0.0f)
#define RFL_SCARA_ARM_JI_TO_BASE_DEFAULT_Z (0.0f)
#define RFL_SCARA_ARM_JI_TO_BASE_DEFAULT_ANGLE_Z (0.0f)
#define RFL_SCARA_ARM_JI_TO_BASE_DEFAULT_ANGLE_Y (0.0f)
#define RFL_SCARA_ARM_JI_TO_BASE_DEFAULT_ANGLE_X (0.0f)

#define RFL_SCARA_ARM_TOOL_TO_J6_DEFAULT_X (0.0f)
#define RFL_SCARA_ARM_TOOL_TO_J6_DEFAULT_Y (0.0f)
#define RFL_SCARA_ARM_TOOL_TO_J6_DEFAULT_Z (0.0f)
#define RFL_SCARA_ARM_TOOL_TO_J6_DEFAULT_ANGLE_Z (RAD_PI)
#define RFL_SCARA_ARM_TOOL_TO_J6_DEFAULT_ANGLE_Y (0.0f)
#define RFL_SCARA_ARM_TOOL_TO_J6_DEFAULT_ANGLE_X (0.0f)

#define RFL_SCARA_ARM_DEFAULT_ARM_1_LENGTH (0.2f)
#define RFL_SCARA_ARM_DEFAULT_ARM_2_LENGTH (0.2f)
#define RFL_SCARA_ARM_DEFAULT_ARM_3_LENGTH (0.1f)
#define RFL_SCARA_ARM_DEFAULT_ARM_4_LENGTH (0.06f)

#define RFL_SCARA_ARM_DEFAULT_JOINT_1_DH_ALPHA (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_1_DH_A (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_1_DH_D (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_1_DH_THETA (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_1_DH_THETA_OFFSET (0.0f)

#define RFL_SCARA_ARM_DEFAULT_JOINT_2_DH_ALPHA (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_2_DH_A (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_2_DH_D (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_2_DH_THETA (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_2_DH_THETA_OFFSET (0.0f)

#define RFL_SCARA_ARM_DEFAULT_JOINT_3_DH_ALPHA (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_3_DH_A (RFL_SCARA_ARM_DEFAULT_ARM_1_LENGTH)
#define RFL_SCARA_ARM_DEFAULT_JOINT_3_DH_D (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_3_DH_THETA (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_3_DH_THETA_OFFSET (0.0f)

#define RFL_SCARA_ARM_DEFAULT_JOINT_4_DH_ALPHA (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_4_DH_A (RFL_SCARA_ARM_DEFAULT_ARM_2_LENGTH)
#define RFL_SCARA_ARM_DEFAULT_JOINT_4_DH_D (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_4_DH_THETA (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_4_DH_THETA_OFFSET (0.0f)

#define RFL_SCARA_ARM_DEFAULT_JOINT_5_DH_ALPHA (RAD_PI / 2.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_5_DH_A (RFL_SCARA_ARM_DEFAULT_ARM_3_LENGTH)
#define RFL_SCARA_ARM_DEFAULT_JOINT_5_DH_D (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_5_DH_THETA (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_5_DH_THETA_OFFSET (RAD_PI / 2.0f)

#define RFL_SCARA_ARM_DEFAULT_JOINT_6_DH_ALPHA (-RAD_PI / 2.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_6_DH_A (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_6_DH_D (RFL_SCARA_ARM_DEFAULT_ARM_4_LENGTH)
#define RFL_SCARA_ARM_DEFAULT_JOINT_6_DH_THETA (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_6_DH_THETA_OFFSET (0.0f)

#define RFL_SCARA_ARM_DEFAULT_JOINT_1_MAX_VALUE (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_1_MIN_VALUE (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_2_MAX_VALUE (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_2_MIN_VALUE (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_3_MAX_VALUE (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_3_MIN_VALUE (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_4_MAX_VALUE (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_4_MIN_VALUE (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_5_MAX_VALUE (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_5_MIN_VALUE (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_6_MAX_VALUE (0.0f)
#define RFL_SCARA_ARM_DEFAULT_JOINT_6_MIN_VALUE (0.0f)

// #define RFL_SCARA_ARM_DEFAULT_JOINT_1_RM_M3508_SPEED_PID_KP (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_1_RM_M3508_SPEED_PID_KI (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_1_RM_M3508_SPEED_PID_KD (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_1_RM_M3508_SPEED_PID_MAX_IOUT (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_1_RM_M3508_SPEED_PID_MAX_OUT (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_1_RM_M3508_ANGLE_PID_KP (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_1_RM_M3508_ANGLE_PID_KI (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_1_RM_M3508_ANGLE_PID_KD (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_1_RM_M3508_ANGLE_PID_MAX_IOUT (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_1_RM_M3508_ANGLE_PID_MAX_OUT (0.0f)

// #define RFL_SCARA_ARM_DEFAULT_JOINT_2_UNITREE_GO_M8010_6_K_ANGLE (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_2_UNITREE_GO_M8010_6_K_SPEED (0.0f)

// #define RFL_SCARA_ARM_DEFAULT_JOINT_3_UNITREE_GO_M8010_6_K_ANGLE (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_3_UNITREE_GO_M8010_6_K_SPEED (0.0f)

// #define RFL_SCARA_ARM_DEFAULT_JOINT_4_RM_M3508_SPEED_PID_KP (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_4_RM_M3508_SPEED_PID_KI (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_4_RM_M3508_SPEED_PID_KD (0.0f)
// #define RRFL_SCARA_ARM_DEFAULT_JOINT_4_RM_M3508_SPEED_PID_MAX_IOUT (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_4_RM_M3508_SPEED_PID_MAX_OUT (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_4_RM_M3508_ANGLE_PID_KP (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_4_RM_M3508_ANGLE_PID_KI (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_4_RM_M3508_ANGLE_PID_KD (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_4_RM_M3508_ANGLE_PID_MAX_IOUT (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_4_RM_M3508_ANGLE_PID_MAX_OUT (0.0f)

// #define RFL_SCARA_ARM_DEFAULT_JOINT_56_RM_M2006_SPEED_PID_KP (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_56_RM_M2006_SPEED_PID_KI (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_56_RM_M2006_SPEED_PID_KD (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_56_RM_M2006_SPEED_PID_MAX_IOUT (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_56_RM_M2006_SPEED_PID_MAX_OUT (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_56_RM_M2006_ANGLE_PID_KP (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_56_RM_M2006_ANGLE_PID_KI (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_56_RM_M2006_ANGLE_PID_KD (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_56_RM_M2006_ANGLE_PID_MAX_IOUT (0.0f)
// #define RFL_SCARA_ARM_DEFAULT_JOINT_56_RM_M2006_ANGLE_PID_MAX_OUT (0.0f)

#endif /* _APP_SCARA_ARM_CONFIG_H__ */
